### ISSUE TITLE
Confusing wording in ESR Search Duration section

### ISSUE THREAD

**Issue by meznak** [dpaper-splunk/public#12]
https://github.com/dpaper-splunk/public/blob/7fba9e548083bdc89984a41fab2878ed8da96c25/dashboards/extended_search_reporting.xml#L269-L355

**Problem:** The term `duration` is already used on this dashboard (and elsewhere in the industry) to refer to a search's run time, but this section is measuring the time period searched. Generally, the term `span` is used for this, including elsewhere on this dashboard. This wording choice has caused confusion in nearly every customer-facing health check I've performed.

**Proposed solution:** Reword this section to refer to a search's span, rather than duration.

**Note:** If accepted, I'm happy to do this work.

**Comment by meznak** [comment]
Same concern for this section:
https://github.com/dpaper-splunk/public/blob/7fba9e548083bdc89984a41fab2878ed8da96c25/dashboards/extended_search_reporting.xml#L139-L209

**Comment by dpaper-splunk** [comment]
Spot on. Span does make more sense. All references to duration in lieu of span have been fixed for v1.7.
